#!/bin/bash
DAY="$1"
mkdir -p inputs/"${DAY}"
touch inputs/"${DAY}"/{input,example}.txt
cat > src/bin/"${DAY}".rs <<EOF
use color_eyre::Result;
fn main() -> Result<()> {
    color_eyre::install()?;
    let input = std::io::read_to_string(std::io::stdin())?;
    Ok(())
}
EOF