#!/bin/bash
DAY="$1"
mkdir -p inputs/"${DAY}"
touch inputs/"${DAY}"/{input,example}.txt
cat > src/bin/"${DAY}".rs <<EOF
use color_eyre::Result;
use std::io;
fn main() -> Result<()> {
    color_eyre::install()?;
    let input = io::read_to_string(io::stdin())?;
    Ok(())
}
EOF